# syntax=docker/dockerfile:1
FROM golang:1.21-alpine AS build
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/loadbalancer ./cmd/loadbalancer

FROM gcr.io/distroless/base-debian12
COPY --from=build /out/loadbalancer /usr/local/bin/loadbalancer
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/loadbalancer"]
